<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <Version>$([System.DateTime]::Now.ToString(yy.MM.dd.HHmm))</Version>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <PackageIcon>组合 1.png</PackageIcon>
      <PackageProjectUrl>https://github.com/Round-Studio/OverrideLauncher.Core</PackageProjectUrl>
      <RepositoryUrl>https://github.com/Round-Studio/OverrideLauncher.Core</RepositoryUrl>
      <Description>新一代 MC 启动器，迅速、快速、轻便！</Description>
      <TargetFrameworks>net8.0</TargetFrameworks>
      <ImplicitUsings>enable</ImplicitUsings>
      <Authors>Round-Studio</Authors>
      <LangVersion>latest</LangVersion>
      <Title>OverrideLauncher</Title>
      <Nullable>disable</Nullable>
      <GenerateDocumentationFile>False</GenerateDocumentationFile>
      <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
      <PackageLicenseUrl>https://github.com/Round-Studio/OverrideLauncher.Core/blob/v2/LICENSE</PackageLicenseUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Downloader" Version="4.0.1-beta" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Classes\Install\DownloadPerformanceMonitor.cs" />
    </ItemGroup>

    <ItemGroup>
      <None Update="组合 1.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
