name: build
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  compile-flags: "-c Release"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: Test
      run: dotnet test OverrideLauncher.Core/OverrideLauncher.Core.csproj
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: Test
      run: dotnet build OverrideLauncher.Core/OverrideLauncher.Core.csproj
  build:
    runs-on: ubuntu-latest
    needs: [test, test_build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: Build OverrideLauncher.Core
      run: dotnet build OverrideLauncher.Core/OverrideLauncher.Core.csproj ${{ env.compile-flags }}
    - name: Set Version
      run : |
        current_date=$(date +"%y.%m.%d.%H%M%S")
        sed -i "s/<Version>[^<]*<\/Version>/<Version>$current_date<\/Version>/" OverrideLauncher.Core/OverrideLauncher.Core.csproj
    - name: Publish OverrideLauncher.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with: 
        PROJECT_FILE_PATH: OverrideLauncher.Core/OverrideLauncher.Core.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}